name: flutter_payment_screen
description: Beautiful and customizable payment screens for Flutter apps with UPI, Card, Wallet and Cash on Delivery support.
version: 0.0.1


homepage: https://github.com/Sakshi-2508/flutter_payment_screen
repository: https://github.com/Sakshi-2508/flutter_payment_screen
issue_tracker: https://github.com/Sakshi-2508/flutter_payment_screen/issues


environment:
  sdk: ^3.11.5
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - example/assets/logos/bhim.jpg
    - example/assets/logos/phonepay.jpg
    - example/assets/logos/paytm.jpg
    - example/assets/logos/gpay.png
