name: flutter_payment_screen
description: A beautiful and customizable payment UI package for Flutter.
version: 0.0.1

environment:
  sdk: ^3.11.5
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - example/assets/logos/bhim.jpg
    - example/assets/logos/phonepay.jpg
    - example/assets/logos/paytm.jpg
    - example/assets/logos/gpay.png
